### ISSUE TITLE
Bug: Control stick left + right + up gives out of bound coordinate

### ISSUE THREAD

**Issue by jamsge** [Crane1195/CL-FW#1]
To reproduce:

1. Plug controller in via USB for PC DInput mode Gamepad Mode (don't hold anything)
2. Open up the Standard Controller config in Dolphin for a visual
3. Hold down both horizontal control stick buttons and up. Looking at the control stick visualizer, it seems that the control stick points to an unintended coordinate.

only one control stick button held down + up, 

![image](https://user-images.githubusercontent.com/36876904/155053572-48e17cbf-abf4-417c-b41e-80e3b52c622f.png)

both control stick buttons held down + up

![image](https://user-images.githubusercontent.com/36876904/155053603-7eb7251a-c0c5-4e7f-96a4-828d71a63540.png)

I could also be wrong and maybe this is intentional.

I am using a controller made with an Arduino Micro.

**Comment by Crane1195** [comment]
Fixed in f6bb134
