### ISSUE TITLE
Bug: Control stick Left + Down + Right gives out of bound coordinate

### ISSUE THREAD

**Issue by jamesondvd** [Crane1195/CL-FW#3]
Device: JFA LBX
Host: USB C cable to PC (Slippi)
Game: Super Smash Bros. Melee (Slippi 2.5.2)
Buttons pressed while plugging in: None
Actions: Hitting left+down, waiting for a bit, then pressing right
Expected behavior: Remain in crouch / Get coordinate for down+right that isn't out of bounds
Actual behavior: Out of bound coordinate causes guaranteed dashback out of crouch / moonwalks result in small dashdance rather than actual moonwalks (with left>down>right method)

This issue is making it to where I can't reliably moonwalk with the left>down>right method, and I also have guaranteed dash back out of crouch which should be banned. I mostly want this gone so I can moonwalk again with my old method on Frame1. Thank you

I realize that this is similar to the issue here: https://github.com/Crane1195/CL-FW/issues/1
but this is a movement problem that has been introduced due to this issue

**Comment by Crane1195** [comment]
Repeat of #1, fixed in commit f6bb134.
