### ISSUE TITLE
C-Stick Activated After Using D-Pad

### ISSUE THREAD

**Issue by sleeping-gryph0n** [Crane1195/CL-FW#4]
- Device: LBX and B0XX R2
- Host: PC (USB C to USB A) and Wii/GameCube (USB C to GC cable)
- Game: Super Smash Bros. Melee
- Buttons pressed while plugging in: None
- Actions:
      1. Mod X + Mod Y
      2. C-Stick Up/Down/Left/Right
      3. Release one or both modifiers
- Expected behavior: A d-pad input of the desired direction followed by no further actions.
- Actual behavior: A d-pad input of the desired direction followed by a c-stick input of the same direction when releasing one or both modifiers.
- Note: This happens most often in Uncle Punch when loading a savestate as there is not a taunt to eat the c-stick inputs.

**Comment by Crane1195** [comment]
If you are holding a c stick button and not modifiers, it is going to input the c stick. I could implement logic to keep track of if a dpad input was just made, but I don't think that's necessary when you can just let go of the c stick button before the modifiers.
