### ISSUE TITLE
Melee, moonwalking impossible to the right. 

### ISSUE THREAD

**Issue by shavark** [Crane1195/CL-FW#7]
When trying to moonwalk to the left.... perfectly fine ( walking left... moon walk input = right > down > left)

Moonwalking to the right seems to be impossible, or atleast impractical. ( walking right... moon walk input = left > down > right) 

Unaware on the coding side, but from the player side it isn't doable as far as I can see. 

Using the cl-fw code on a lbx.

**Comment by Crane1195** [comment]
Repeat of #1, fixed in commit f6bb134.
